// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScheduling.Infrastructure.Persistence;

#nullable disable

namespace SmartScheduling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427233254_AddFuncionarioPrimeiroAtendimento")]
    partial class AddFuncionarioPrimeiroAtendimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuncionarioServico", b =>
                {
                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicosId")
                        .HasColumnType("uuid");

                    b.HasKey("FuncionarioId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("funcionario_servicos", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_agendamentos_cliente_id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_agendamentos_estabelecimento_id");

                    b.HasIndex("FuncionarioId")
                        .HasDatabaseName("ix_agendamentos_funcionario_id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("FuncionarioId", "Status")
                        .HasDatabaseName("ix_agendamentos_funcionario_status");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_clientes_estabelecimento_id");

                    b.HasIndex("EstabelecimentoId", "Email")
                        .HasDatabaseName("ix_clientes_estabelecimento_email");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Conversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgendamentoPendenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("agendamento_pendente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_conversas_estabelecimento_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_conversas_status");

                    b.ToTable("conversas", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Estabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("FuncionarioIdPrimeiroAtendimento")
                        .HasColumnType("uuid")
                        .HasColumnName("funcionario_primeiro_atendimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("ProprietarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proprietario_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("whatsapp_phone_number_id");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioIdPrimeiroAtendimento");

                    b.HasIndex("WhatsAppPhoneNumberId")
                        .IsUnique()
                        .HasDatabaseName("ix_estabelecimentos_whatsapp_phone_number_id");

                    b.ToTable("estabelecimentos", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.EstablishmentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "DataInicio", "DataFim")
                        .HasDatabaseName("ix_bloqueios_estabelecimento_estabelecimento_periodo");

                    b.ToTable("bloqueios_estabelecimento", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.EstablishmentWorkingHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId", "DiaSemana")
                        .HasDatabaseName("ix_horarios_estabelecimento_estabelecimento_dia");

                    b.ToTable("horarios_estabelecimento", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_funcionarios_estabelecimento_id");

                    b.HasIndex("EstabelecimentoId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_estabelecimento_email");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Mensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversa_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("TextoTranscrito")
                        .HasColumnType("text")
                        .HasColumnName("texto_transcrito");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<bool>("VeioDoCliente")
                        .HasColumnType("boolean")
                        .HasColumnName("veio_do_cliente");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId")
                        .HasDatabaseName("ix_mensagens_conversa_id");

                    b.ToTable("mensagens", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.RecurringSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("EstablishmentId", "IsActive");

                    b.ToTable("RecurringSchedules");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<Guid>("EstabelecimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("estabelecimento_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId")
                        .HasDatabaseName("ix_servicos_estabelecimento_id");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuncionarioServico", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartScheduling.Domain.Entities.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduling.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Agendamentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduling.Domain.Entities.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SmartScheduling.Domain.ValueObjects.TimeSlot", "Horario", b1 =>
                        {
                            b1.Property<Guid>("AgendamentoId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fim_em");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio_em");

                            b1.HasKey("AgendamentoId");

                            b1.ToTable("agendamentos");

                            b1.WithOwner()
                                .HasForeignKey("AgendamentoId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Horario")
                        .IsRequired();

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("SmartScheduling.Domain.ValueObjects.PhoneNumber", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone");

                            b1.HasKey("ClienteId");

                            b1.ToTable("clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Telefone")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Conversa", b =>
                {
                    b.OwnsOne("SmartScheduling.Domain.ValueObjects.PhoneNumber", "TelefoneCliente", b1 =>
                        {
                            b1.Property<Guid>("ConversaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone_cliente");

                            b1.HasKey("ConversaId");

                            b1.ToTable("conversas");

                            b1.WithOwner()
                                .HasForeignKey("ConversaId");
                        });

                    b.Navigation("TelefoneCliente")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Estabelecimento", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioIdPrimeiroAtendimento")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.EstablishmentBlock", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.EstablishmentWorkingHours", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany()
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Estabelecimento", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("SmartScheduling.Domain.ValueObjects.WorkingHours", "Horarios", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer")
                                .HasColumnName("dia_semana");

                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_fim");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone")
                                .HasColumnName("hora_inicio");

                            b1.Property<Guid>("funcionario_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("funcionario_id");

                            b1.ToTable("horarios_trabalho", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("funcionario_id");
                        });

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Mensagem", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Conversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.RecurringSchedule", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduling.Domain.Entities.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartScheduling.Domain.Entities.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Servico", b =>
                {
                    b.HasOne("SmartScheduling.Domain.Entities.Estabelecimento", null)
                        .WithMany("Servicos")
                        .HasForeignKey("EstabelecimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Conversa", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Estabelecimento", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("SmartScheduling.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
